server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    # 表示是否将自己注册进eureka默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka