server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka

ribbon:
  ReadTimeout: 5000     #指的是建立连接所需要的时间
  ConnectTimeout: 5000  #指的是建立连接后从服务器读取到可用资源所用的时间

#用于服务降级在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true
