server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处要配置rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于bindings整合
          type: rabbit # 消息组件类型
          environment:
            spring:
              rabbitmq:
                host: 172.16.11.109
                port: 5672
                username: admin
                password: admin
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称，不是固定的，可以自定义
          destination: demoExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本文则设置"text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka
