server:
  port: 9527

spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #payment_route 路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment_route2 #payment_route 路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka